### ISSUE TITLE
Small feature: Allow deletion of all cropped areas

### ISSUE THREAD

**Issue by paddington1983** [tapmodo/Jcrop#182]
Currently it is not possible to delete all areas: in the function requestDelete around line 2350 there is a check on "this.ui.multi.length > 1". I can delete areas if there are two or more left, but never the last one. However it can be nice to be able to delete all areas and allow the user to start with a clean image. 

I am not too familiar with this plugin so I changed the above check to "this.ui.multi.length > 0" and then I changed the function deleteSelection to :

    deleteSelection: function () {
            if (this.ui.selection) {
            	this.removeSelection(this.ui.selection);
	            if (this.ui.multi[0]) {
		            this.ui.multi[0].focus();
	            } else {
		            var max = this.getContainerSize();
	            	var selection = {
		            	w: max[0],
						x: 0,
						x2: max[0],
						h: max[1],
						y: 0,
						y2: max[1]
		            }
		            this.ui.selection.redraw(selection);
	            }
		        this.ui.selection.refresh();
            }
        }

Probably a clumsy solution but maybe it will help you with a clean solution. Thanks in advance :)

**Comment by tapmodo** [comment]
It's intentional that you can't delete the last one.
In 0.9.x versions, there was a sense of "selected" or nothing selected.
In 2.x versions, (ideally) it's intended that something is selected at all times.

**Below references newest version of WIP-2.x branch**
If you wanted to do this, a better workaround is to add a new API method.
(Re-write or polyfill the forEach method if your environment doesn't support it.)

```javascript
$.Jcrop.prototype.deleteAll = function() {
  var self = this;
  this.ui.multi.forEach(function(item){
    self.deleteSelection(item);
  });
};

var jcp = $("#target").Jcrop('api');
jcp.deleteAll();
```

This exposes an additional display bug referened in Issue #202 
I'm going to close this one since it isn't *per se* an issue.

**Comment by tablatronix** [comment]
This should be a feature, i do not like new presumption that something should always be selected.
