### ISSUE TITLE
Any complete docs?

### ISSUE THREAD

**Issue by nathanhornby** [tapmodo/Jcrop#211]
Hi there,

I've checked out the docs over at http://deepliquid.com/content/Jcrop_Manual.html#Setting_Options but they seem to be missing options that are available for the plugin.

I'm using some code provided to me by a member of the Meteor community that is using options such as `bgFade`, `boxWidth` and `boxHeight`. Are they documented anywhere?

I found a [blog post](http://deepliquid.com/blog/archives/166) where you announce the inclusion of `bgFade`, but don't explain what it does.

Thanks!

**Comment by tapmodo** [comment]
Keeping up with the sites and documentation has been very difficult. Protip: use the WIP-2.x branch, and jcrop.org should have the most relevant docs for that. They're more complete than the 0.9.x code and docs, which are basically no longer supported. I'm going to close this mostly because it's a seriously known issue, and believe it or not, I'm working on it!
